version: '3'
services:
  db:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    environment: 
      - MYSQL_DATABASE=gencau
      - MYSQL_ROOT_PASSWORD=root
    command: --authentication_policy=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./db_data_node:/usr/data
    ports:
      - 3306:3306
    networks:
      - mynetwork

  # app: 
  #   build:
  #     context: .
  #     dockerfile: docker/nodejs/Dockerfile
  #   command: npm start
  #   ports: 
  #     - '3000:3000'
  #   volumes: 
  #     - ./src:/usr/app
  #   depends_on: 
  #     - db
  #   links:
  #     - db
  #   networks:
  #     - mynetwork    

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "phpmyadmin-srv"
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - db
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db_data_node: